<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class KotaSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $kota = array(
            array('id' => '1102', 'propinsi_id' => '11', 'nama' => 'KABUPATEN SIMEULUE'),
            array('id' => '1101', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH SINGKIL'),
            array('id' => '1103', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH SELATAN'),
            array('id' => '1104', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH TENGGARA'),
            array('id' => '1105', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH TIMUR'),
            array('id' => '1106', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH TENGAH'),
            array('id' => '1107', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH BARAT'),
            array('id' => '1108', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH BESAR'),
            array('id' => '1109', 'propinsi_id' => '11', 'nama' => 'KABUPATEN PIDIE'),
            array('id' => '1110', 'propinsi_id' => '11', 'nama' => 'KABUPATEN BIREUEN'),
            array('id' => '1111', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH UTARA'),
            array('id' => '1112', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH BARAT DAYA'),
            array('id' => '1113', 'propinsi_id' => '11', 'nama' => 'KABUPATEN GAYO LUES'),
            array('id' => '1114', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH TAMIANG'),
            array('id' => '1115', 'propinsi_id' => '11', 'nama' => 'KABUPATEN NAGAN RAYA'),
            array('id' => '1116', 'propinsi_id' => '11', 'nama' => 'KABUPATEN ACEH JAYA'),
            array('id' => '1117', 'propinsi_id' => '11', 'nama' => 'KABUPATEN BENER MERIAH'),
            array('id' => '1118', 'propinsi_id' => '11', 'nama' => 'KABUPATEN PIDIE JAYA'),
            array('id' => '1171', 'propinsi_id' => '11', 'nama' => 'KOTA BANDA ACEH'),
            array('id' => '1172', 'propinsi_id' => '11', 'nama' => 'KOTA SABANG'),
            array('id' => '1173', 'propinsi_id' => '11', 'nama' => 'KOTA LANGSA'),
            array('id' => '1174', 'propinsi_id' => '11', 'nama' => 'KOTA LHOKSEUMAWE'),
            array('id' => '1175', 'propinsi_id' => '11', 'nama' => 'KOTA SUBULUSSALAM'),
            array('id' => '1201', 'propinsi_id' => '12', 'nama' => 'KABUPATEN NIAS'),
            array('id' => '1202', 'propinsi_id' => '12', 'nama' => 'KABUPATEN MANDAILING NATAL'),
            array('id' => '1203', 'propinsi_id' => '12', 'nama' => 'KABUPATEN TAPANULI SELATAN'),
            array('id' => '1204', 'propinsi_id' => '12', 'nama' => 'KABUPATEN TAPANULI TENGAH'),
            array('id' => '1205', 'propinsi_id' => '12', 'nama' => 'KABUPATEN TAPANULI UTARA'),
            array('id' => '1206', 'propinsi_id' => '12', 'nama' => 'KABUPATEN TOBA SAMOSIR'),
            array('id' => '1207', 'propinsi_id' => '12', 'nama' => 'KABUPATEN LABUHAN BATU'),
            array('id' => '1208', 'propinsi_id' => '12', 'nama' => 'KABUPATEN ASAHAN'),
            array('id' => '1209', 'propinsi_id' => '12', 'nama' => 'KABUPATEN SIMALUNGUN'),
            array('id' => '1210', 'propinsi_id' => '12', 'nama' => 'KABUPATEN DAIRI'),
            array('id' => '1211', 'propinsi_id' => '12', 'nama' => 'KABUPATEN KARO'),
            array('id' => '1212', 'propinsi_id' => '12', 'nama' => 'KABUPATEN DELI SERDANG'),
            array('id' => '1213', 'propinsi_id' => '12', 'nama' => 'KABUPATEN LANGKAT'),
            array('id' => '1214', 'propinsi_id' => '12', 'nama' => 'KABUPATEN NIAS SELATAN'),
            array('id' => '1215', 'propinsi_id' => '12', 'nama' => 'KABUPATEN HUMBANG HASUNDUTAN'),
            array('id' => '1216', 'propinsi_id' => '12', 'nama' => 'KABUPATEN PAKPAK BHARAT'),
            array('id' => '1217', 'propinsi_id' => '12', 'nama' => 'KABUPATEN SAMOSIR'),
            array('id' => '1218', 'propinsi_id' => '12', 'nama' => 'KABUPATEN SERDANG BEDAGAI'),
            array('id' => '1219', 'propinsi_id' => '12', 'nama' => 'KABUPATEN BATU BARA'),
            array('id' => '1220', 'propinsi_id' => '12', 'nama' => 'KABUPATEN PADANG LAWAS UTARA'),
            array('id' => '1221', 'propinsi_id' => '12', 'nama' => 'KABUPATEN PADANG LAWAS'),
            array('id' => '1222', 'propinsi_id' => '12', 'nama' => 'KABUPATEN LABUHAN BATU SELATAN'),
            array('id' => '1223', 'propinsi_id' => '12', 'nama' => 'KABUPATEN LABUHAN BATU UTARA'),
            array('id' => '1224', 'propinsi_id' => '12', 'nama' => 'KABUPATEN NIAS UTARA'),
            array('id' => '1225', 'propinsi_id' => '12', 'nama' => 'KABUPATEN NIAS BARAT'),
            array('id' => '1271', 'propinsi_id' => '12', 'nama' => 'KOTA SIBOLGA'),
            array('id' => '1272', 'propinsi_id' => '12', 'nama' => 'KOTA TANJUNG BALAI'),
            array('id' => '1273', 'propinsi_id' => '12', 'nama' => 'KOTA PEMATANG SIANTAR'),
            array('id' => '1274', 'propinsi_id' => '12', 'nama' => 'KOTA TEBING TINGGI'),
            array('id' => '1275', 'propinsi_id' => '12', 'nama' => 'KOTA MEDAN'),
            array('id' => '1276', 'propinsi_id' => '12', 'nama' => 'KOTA BINJAI'),
            array('id' => '1277', 'propinsi_id' => '12', 'nama' => 'KOTA PADANGSIDIMPUAN'),
            array('id' => '1278', 'propinsi_id' => '12', 'nama' => 'KOTA GUNUNGSITOLI'),
            array('id' => '1301', 'propinsi_id' => '13', 'nama' => 'KABUPATEN KEPULAUAN MENTAWAI'),
            array('id' => '1302', 'propinsi_id' => '13', 'nama' => 'KABUPATEN PESISIR SELATAN'),
            array('id' => '1303', 'propinsi_id' => '13', 'nama' => 'KABUPATEN SOLOK'),
            array('id' => '1304', 'propinsi_id' => '13', 'nama' => 'KABUPATEN SIJUNJUNG'),
            array('id' => '1305', 'propinsi_id' => '13', 'nama' => 'KABUPATEN TANAH DATAR'),
            array('id' => '1306', 'propinsi_id' => '13', 'nama' => 'KABUPATEN PADANG PARIAMAN'),
            array('id' => '1307', 'propinsi_id' => '13', 'nama' => 'KABUPATEN AGAM'),
            array('id' => '1308', 'propinsi_id' => '13', 'nama' => 'KABUPATEN LIMA PULUH KOTA'),
            array('id' => '1309', 'propinsi_id' => '13', 'nama' => 'KABUPATEN PASAMAN'),
            array('id' => '1310', 'propinsi_id' => '13', 'nama' => 'KABUPATEN SOLOK SELATAN'),
            array('id' => '1311', 'propinsi_id' => '13', 'nama' => 'KABUPATEN DHARMASRAYA'),
            array('id' => '1312', 'propinsi_id' => '13', 'nama' => 'KABUPATEN PASAMAN BARAT'),
            array('id' => '1371', 'propinsi_id' => '13', 'nama' => 'KOTA PADANG'),
            array('id' => '1372', 'propinsi_id' => '13', 'nama' => 'KOTA SOLOK'),
            array('id' => '1373', 'propinsi_id' => '13', 'nama' => 'KOTA SAWAH LUNTO'),
            array('id' => '1374', 'propinsi_id' => '13', 'nama' => 'KOTA PADANG PANJANG'),
            array('id' => '1375', 'propinsi_id' => '13', 'nama' => 'KOTA BUKITTINGGI'),
            array('id' => '1376', 'propinsi_id' => '13', 'nama' => 'KOTA PAYAKUMBUH'),
            array('id' => '1377', 'propinsi_id' => '13', 'nama' => 'KOTA PARIAMAN'),
            array('id' => '1401', 'propinsi_id' => '14', 'nama' => 'KABUPATEN KUANTAN SINGINGI'),
            array('id' => '1402', 'propinsi_id' => '14', 'nama' => 'KABUPATEN INDRAGIRI HULU'),
            array('id' => '1403', 'propinsi_id' => '14', 'nama' => 'KABUPATEN INDRAGIRI HILIR'),
            array('id' => '1404', 'propinsi_id' => '14', 'nama' => 'KABUPATEN PELALAWAN'),
            array('id' => '1405', 'propinsi_id' => '14', 'nama' => 'KABUPATEN S I A K'),
            array('id' => '1406', 'propinsi_id' => '14', 'nama' => 'KABUPATEN KAMPAR'),
            array('id' => '1407', 'propinsi_id' => '14', 'nama' => 'KABUPATEN ROKAN HULU'),
            array('id' => '1408', 'propinsi_id' => '14', 'nama' => 'KABUPATEN BENGKALIS'),
            array('id' => '1409', 'propinsi_id' => '14', 'nama' => 'KABUPATEN ROKAN HILIR'),
            array('id' => '1410', 'propinsi_id' => '14', 'nama' => 'KABUPATEN KEPULAUAN MERANTI'),
            array('id' => '1471', 'propinsi_id' => '14', 'nama' => 'KOTA PEKANBARU'),
            array('id' => '1473', 'propinsi_id' => '14', 'nama' => 'KOTA D U M A I'),
            array('id' => '1501', 'propinsi_id' => '15', 'nama' => 'KABUPATEN KERINCI'),
            array('id' => '1502', 'propinsi_id' => '15', 'nama' => 'KABUPATEN MERANGIN'),
            array('id' => '1503', 'propinsi_id' => '15', 'nama' => 'KABUPATEN SAROLANGUN'),
            array('id' => '1504', 'propinsi_id' => '15', 'nama' => 'KABUPATEN BATANG HARI'),
            array('id' => '1505', 'propinsi_id' => '15', 'nama' => 'KABUPATEN MUARO JAMBI'),
            array('id' => '1506', 'propinsi_id' => '15', 'nama' => 'KABUPATEN TANJUNG JABUNG TIMUR'),
            array('id' => '1507', 'propinsi_id' => '15', 'nama' => 'KABUPATEN TANJUNG JABUNG BARAT'),
            array('id' => '1508', 'propinsi_id' => '15', 'nama' => 'KABUPATEN TEBO'),
            array('id' => '1509', 'propinsi_id' => '15', 'nama' => 'KABUPATEN BUNGO'),
            array('id' => '1571', 'propinsi_id' => '15', 'nama' => 'KOTA JAMBI'),
            array('id' => '1572', 'propinsi_id' => '15', 'nama' => 'KOTA SUNGAI PENUH'),
            array('id' => '1601', 'propinsi_id' => '16', 'nama' => 'KABUPATEN OGAN KOMERING ULU'),
            array('id' => '1602', 'propinsi_id' => '16', 'nama' => 'KABUPATEN OGAN KOMERING ILIR'),
            array('id' => '1603', 'propinsi_id' => '16', 'nama' => 'KABUPATEN MUARA ENIM'),
            array('id' => '1604', 'propinsi_id' => '16', 'nama' => 'KABUPATEN LAHAT'),
            array('id' => '1605', 'propinsi_id' => '16', 'nama' => 'KABUPATEN MUSI RAWAS'),
            array('id' => '1606', 'propinsi_id' => '16', 'nama' => 'KABUPATEN MUSI BANYUASIN'),
            array('id' => '1607', 'propinsi_id' => '16', 'nama' => 'KABUPATEN BANYU ASIN'),
            array('id' => '1608', 'propinsi_id' => '16', 'nama' => 'KABUPATEN OGAN KOMERING ULU SELATAN'),
            array('id' => '1609', 'propinsi_id' => '16', 'nama' => 'KABUPATEN OGAN KOMERING ULU TIMUR'),
            array('id' => '1610', 'propinsi_id' => '16', 'nama' => 'KABUPATEN OGAN ILIR'),
            array('id' => '1611', 'propinsi_id' => '16', 'nama' => 'KABUPATEN EMPAT LAWANG'),
            array('id' => '1612', 'propinsi_id' => '16', 'nama' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'),
            array('id' => '1613', 'propinsi_id' => '16', 'nama' => 'KABUPATEN MUSI RAWAS UTARA'),
            array('id' => '1671', 'propinsi_id' => '16', 'nama' => 'KOTA PALEMBANG'),
            array('id' => '1672', 'propinsi_id' => '16', 'nama' => 'KOTA PRABUMULIH'),
            array('id' => '1673', 'propinsi_id' => '16', 'nama' => 'KOTA PAGAR ALAM'),
            array('id' => '1674', 'propinsi_id' => '16', 'nama' => 'KOTA LUBUKLINGGAU'),
            array('id' => '1701', 'propinsi_id' => '17', 'nama' => 'KABUPATEN BENGKULU SELATAN'),
            array('id' => '1702', 'propinsi_id' => '17', 'nama' => 'KABUPATEN REJANG LEBONG'),
            array('id' => '1703', 'propinsi_id' => '17', 'nama' => 'KABUPATEN BENGKULU UTARA'),
            array('id' => '1704', 'propinsi_id' => '17', 'nama' => 'KABUPATEN KAUR'),
            array('id' => '1705', 'propinsi_id' => '17', 'nama' => 'KABUPATEN SELUMA'),
            array('id' => '1706', 'propinsi_id' => '17', 'nama' => 'KABUPATEN MUKOMUKO'),
            array('id' => '1707', 'propinsi_id' => '17', 'nama' => 'KABUPATEN LEBONG'),
            array('id' => '1708', 'propinsi_id' => '17', 'nama' => 'KABUPATEN KEPAHIANG'),
            array('id' => '1709', 'propinsi_id' => '17', 'nama' => 'KABUPATEN BENGKULU TENGAH'),
            array('id' => '1771', 'propinsi_id' => '17', 'nama' => 'KOTA BENGKULU'),
            array('id' => '1801', 'propinsi_id' => '18', 'nama' => 'KABUPATEN LAMPUNG BARAT'),
            array('id' => '1802', 'propinsi_id' => '18', 'nama' => 'KABUPATEN TANGGAMUS'),
            array('id' => '1803', 'propinsi_id' => '18', 'nama' => 'KABUPATEN LAMPUNG SELATAN'),
            array('id' => '1804', 'propinsi_id' => '18', 'nama' => 'KABUPATEN LAMPUNG TIMUR'),
            array('id' => '1805', 'propinsi_id' => '18', 'nama' => 'KABUPATEN LAMPUNG TENGAH'),
            array('id' => '1806', 'propinsi_id' => '18', 'nama' => 'KABUPATEN LAMPUNG UTARA'),
            array('id' => '1807', 'propinsi_id' => '18', 'nama' => 'KABUPATEN WAY KANAN'),
            array('id' => '1808', 'propinsi_id' => '18', 'nama' => 'KABUPATEN TULANGBAWANG'),
            array('id' => '1809', 'propinsi_id' => '18', 'nama' => 'KABUPATEN PESAWARAN'),
            array('id' => '1810', 'propinsi_id' => '18', 'nama' => 'KABUPATEN PRINGSEWU'),
            array('id' => '1811', 'propinsi_id' => '18', 'nama' => 'KABUPATEN MESUJI'),
            array('id' => '1812', 'propinsi_id' => '18', 'nama' => 'KABUPATEN TULANG BAWANG BARAT'),
            array('id' => '1813', 'propinsi_id' => '18', 'nama' => 'KABUPATEN PESISIR BARAT'),
            array('id' => '1871', 'propinsi_id' => '18', 'nama' => 'KOTA BANDAR LAMPUNG'),
            array('id' => '1872', 'propinsi_id' => '18', 'nama' => 'KOTA METRO'),
            array('id' => '1901', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BANGKA'),
            array('id' => '1902', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BELITUNG'),
            array('id' => '1903', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BANGKA BARAT'),
            array('id' => '1904', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BANGKA TENGAH'),
            array('id' => '1905', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BANGKA SELATAN'),
            array('id' => '1906', 'propinsi_id' => '19', 'nama' => 'KABUPATEN BELITUNG TIMUR'),
            array('id' => '1971', 'propinsi_id' => '19', 'nama' => 'KOTA PANGKAL PINANG'),
            array('id' => '2101', 'propinsi_id' => '21', 'nama' => 'KABUPATEN KARIMUN'),
            array('id' => '2102', 'propinsi_id' => '21', 'nama' => 'KABUPATEN BINTAN'),
            array('id' => '2103', 'propinsi_id' => '21', 'nama' => 'KABUPATEN NATUNA'),
            array('id' => '2104', 'propinsi_id' => '21', 'nama' => 'KABUPATEN LINGGA'),
            array('id' => '2105', 'propinsi_id' => '21', 'nama' => 'KABUPATEN KEPULAUAN ANAMBAS'),
            array('id' => '2171', 'propinsi_id' => '21', 'nama' => 'KOTA B A T A M'),
            array('id' => '2172', 'propinsi_id' => '21', 'nama' => 'KOTA TANJUNG PINANG'),
            array('id' => '3101', 'propinsi_id' => '31', 'nama' => 'KABUPATEN KEPULAUAN SERIBU'),
            array('id' => '3171', 'propinsi_id' => '31', 'nama' => 'KOTA JAKARTA SELATAN'),
            array('id' => '3172', 'propinsi_id' => '31', 'nama' => 'KOTA JAKARTA TIMUR'),
            array('id' => '3173', 'propinsi_id' => '31', 'nama' => 'KOTA JAKARTA PUSAT'),
            array('id' => '3174', 'propinsi_id' => '31', 'nama' => 'KOTA JAKARTA BARAT'),
            array('id' => '3175', 'propinsi_id' => '31', 'nama' => 'KOTA JAKARTA UTARA'),
            array('id' => '3201', 'propinsi_id' => '32', 'nama' => 'KABUPATEN BOGOR'),
            array('id' => '3202', 'propinsi_id' => '32', 'nama' => 'KABUPATEN SUKABUMI'),
            array('id' => '3203', 'propinsi_id' => '32', 'nama' => 'KABUPATEN CIANJUR'),
            array('id' => '3204', 'propinsi_id' => '32', 'nama' => 'KABUPATEN BANDUNG'),
            array('id' => '3205', 'propinsi_id' => '32', 'nama' => 'KABUPATEN GARUT'),
            array('id' => '3206', 'propinsi_id' => '32', 'nama' => 'KABUPATEN TASIKMALAYA'),
            array('id' => '3207', 'propinsi_id' => '32', 'nama' => 'KABUPATEN CIAMIS'),
            array('id' => '3208', 'propinsi_id' => '32', 'nama' => 'KABUPATEN KUNINGAN'),
            array('id' => '3209', 'propinsi_id' => '32', 'nama' => 'KABUPATEN CIREBON'),
            array('id' => '3210', 'propinsi_id' => '32', 'nama' => 'KABUPATEN MAJALENGKA'),
            array('id' => '3211', 'propinsi_id' => '32', 'nama' => 'KABUPATEN SUMEDANG'),
            array('id' => '3212', 'propinsi_id' => '32', 'nama' => 'KABUPATEN INDRAMAYU'),
            array('id' => '3213', 'propinsi_id' => '32', 'nama' => 'KABUPATEN SUBANG'),
            array('id' => '3214', 'propinsi_id' => '32', 'nama' => 'KABUPATEN PURWAKARTA'),
            array('id' => '3215', 'propinsi_id' => '32', 'nama' => 'KABUPATEN KARAWANG'),
            array('id' => '3216', 'propinsi_id' => '32', 'nama' => 'KABUPATEN BEKASI'),
            array('id' => '3217', 'propinsi_id' => '32', 'nama' => 'KABUPATEN BANDUNG BARAT'),
            array('id' => '3218', 'propinsi_id' => '32', 'nama' => 'KABUPATEN PANGANDARAN'),
            array('id' => '3271', 'propinsi_id' => '32', 'nama' => 'KOTA BOGOR'),
            array('id' => '3272', 'propinsi_id' => '32', 'nama' => 'KOTA SUKABUMI'),
            array('id' => '3273', 'propinsi_id' => '32', 'nama' => 'KOTA BANDUNG'),
            array('id' => '3274', 'propinsi_id' => '32', 'nama' => 'KOTA CIREBON'),
            array('id' => '3275', 'propinsi_id' => '32', 'nama' => 'KOTA BEKASI'),
            array('id' => '3276', 'propinsi_id' => '32', 'nama' => 'KOTA DEPOK'),
            array('id' => '3277', 'propinsi_id' => '32', 'nama' => 'KOTA CIMAHI'),
            array('id' => '3278', 'propinsi_id' => '32', 'nama' => 'KOTA TASIKMALAYA'),
            array('id' => '3279', 'propinsi_id' => '32', 'nama' => 'KOTA BANJAR'),
            array('id' => '3301', 'propinsi_id' => '33', 'nama' => 'KABUPATEN CILACAP'),
            array('id' => '3302', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BANYUMAS'),
            array('id' => '3303', 'propinsi_id' => '33', 'nama' => 'KABUPATEN PURBALINGGA'),
            array('id' => '3304', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BANJARNEGARA'),
            array('id' => '3305', 'propinsi_id' => '33', 'nama' => 'KABUPATEN KEBUMEN'),
            array('id' => '3306', 'propinsi_id' => '33', 'nama' => 'KABUPATEN PURWOREJO'),
            array('id' => '3307', 'propinsi_id' => '33', 'nama' => 'KABUPATEN WONOSOBO'),
            array('id' => '3308', 'propinsi_id' => '33', 'nama' => 'KABUPATEN MAGELANG'),
            array('id' => '3309', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BOYOLALI'),
            array('id' => '3310', 'propinsi_id' => '33', 'nama' => 'KABUPATEN KLATEN'),
            array('id' => '3311', 'propinsi_id' => '33', 'nama' => 'KABUPATEN SUKOHARJO'),
            array('id' => '3312', 'propinsi_id' => '33', 'nama' => 'KABUPATEN WONOGIRI'),
            array('id' => '3313', 'propinsi_id' => '33', 'nama' => 'KABUPATEN KARANGANYAR'),
            array('id' => '3314', 'propinsi_id' => '33', 'nama' => 'KABUPATEN SRAGEN'),
            array('id' => '3315', 'propinsi_id' => '33', 'nama' => 'KABUPATEN GROBOGAN'),
            array('id' => '3316', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BLORA'),
            array('id' => '3317', 'propinsi_id' => '33', 'nama' => 'KABUPATEN REMBANG'),
            array('id' => '3318', 'propinsi_id' => '33', 'nama' => 'KABUPATEN PATI'),
            array('id' => '3319', 'propinsi_id' => '33', 'nama' => 'KABUPATEN KUDUS'),
            array('id' => '3320', 'propinsi_id' => '33', 'nama' => 'KABUPATEN JEPARA'),
            array('id' => '3321', 'propinsi_id' => '33', 'nama' => 'KABUPATEN DEMAK'),
            array('id' => '3322', 'propinsi_id' => '33', 'nama' => 'KABUPATEN SEMARANG'),
            array('id' => '3323', 'propinsi_id' => '33', 'nama' => 'KABUPATEN TEMANGGUNG'),
            array('id' => '3324', 'propinsi_id' => '33', 'nama' => 'KABUPATEN KENDAL'),
            array('id' => '3325', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BATANG'),
            array('id' => '3326', 'propinsi_id' => '33', 'nama' => 'KABUPATEN PEKALONGAN'),
            array('id' => '3327', 'propinsi_id' => '33', 'nama' => 'KABUPATEN PEMALANG'),
            array('id' => '3328', 'propinsi_id' => '33', 'nama' => 'KABUPATEN TEGAL'),
            array('id' => '3329', 'propinsi_id' => '33', 'nama' => 'KABUPATEN BREBES'),
            array('id' => '3371', 'propinsi_id' => '33', 'nama' => 'KOTA MAGELANG'),
            array('id' => '3372', 'propinsi_id' => '33', 'nama' => 'KOTA SURAKARTA'),
            array('id' => '3373', 'propinsi_id' => '33', 'nama' => 'KOTA SALATIGA'),
            array('id' => '3374', 'propinsi_id' => '33', 'nama' => 'KOTA SEMARANG'),
            array('id' => '3375', 'propinsi_id' => '33', 'nama' => 'KOTA PEKALONGAN'),
            array('id' => '3376', 'propinsi_id' => '33', 'nama' => 'KOTA TEGAL'),
            array('id' => '3401', 'propinsi_id' => '34', 'nama' => 'KABUPATEN KULON PROGO'),
            array('id' => '3402', 'propinsi_id' => '34', 'nama' => 'KABUPATEN BANTUL'),
            array('id' => '3403', 'propinsi_id' => '34', 'nama' => 'KABUPATEN GUNUNG KIDUL'),
            array('id' => '3404', 'propinsi_id' => '34', 'nama' => 'KABUPATEN SLEMAN'),
            array('id' => '3471', 'propinsi_id' => '34', 'nama' => 'KOTA YOGYAKARTA'),
            array('id' => '3501', 'propinsi_id' => '35', 'nama' => 'KABUPATEN PACITAN'),
            array('id' => '3502', 'propinsi_id' => '35', 'nama' => 'KABUPATEN PONOROGO'),
            array('id' => '3503', 'propinsi_id' => '35', 'nama' => 'KABUPATEN TRENGGALEK'),
            array('id' => '3504', 'propinsi_id' => '35', 'nama' => 'KABUPATEN TULUNGAGUNG'),
            array('id' => '3505', 'propinsi_id' => '35', 'nama' => 'KABUPATEN BLITAR'),
            array('id' => '3506', 'propinsi_id' => '35', 'nama' => 'KABUPATEN KEDIRI'),
            array('id' => '3507', 'propinsi_id' => '35', 'nama' => 'KABUPATEN MALANG'),
            array('id' => '3508', 'propinsi_id' => '35', 'nama' => 'KABUPATEN LUMAJANG'),
            array('id' => '3509', 'propinsi_id' => '35', 'nama' => 'KABUPATEN JEMBER'),
            array('id' => '3510', 'propinsi_id' => '35', 'nama' => 'KABUPATEN BANYUWANGI'),
            array('id' => '3511', 'propinsi_id' => '35', 'nama' => 'KABUPATEN BONDOWOSO'),
            array('id' => '3512', 'propinsi_id' => '35', 'nama' => 'KABUPATEN SITUBONDO'),
            array('id' => '3513', 'propinsi_id' => '35', 'nama' => 'KABUPATEN PROBOLINGGO'),
            array('id' => '3514', 'propinsi_id' => '35', 'nama' => 'KABUPATEN PASURUAN'),
            array('id' => '3515', 'propinsi_id' => '35', 'nama' => 'KABUPATEN SIDOARJO'),
            array('id' => '3516', 'propinsi_id' => '35', 'nama' => 'KABUPATEN MOJOKERTO'),
            array('id' => '3517', 'propinsi_id' => '35', 'nama' => 'KABUPATEN JOMBANG'),
            array('id' => '3518', 'propinsi_id' => '35', 'nama' => 'KABUPATEN NGANJUK'),
            array('id' => '3519', 'propinsi_id' => '35', 'nama' => 'KABUPATEN MADIUN'),
            array('id' => '3520', 'propinsi_id' => '35', 'nama' => 'KABUPATEN MAGETAN'),
            array('id' => '3521', 'propinsi_id' => '35', 'nama' => 'KABUPATEN NGAWI'),
            array('id' => '3522', 'propinsi_id' => '35', 'nama' => 'KABUPATEN BOJONEGORO'),
            array('id' => '3523', 'propinsi_id' => '35', 'nama' => 'KABUPATEN TUBAN'),
            array('id' => '3524', 'propinsi_id' => '35', 'nama' => 'KABUPATEN LAMONGAN'),
            array('id' => '3525', 'propinsi_id' => '35', 'nama' => 'KABUPATEN GRESIK'),
            array('id' => '3526', 'propinsi_id' => '35', 'nama' => 'KABUPATEN BANGKALAN'),
            array('id' => '3527', 'propinsi_id' => '35', 'nama' => 'KABUPATEN SAMPANG'),
            array('id' => '3528', 'propinsi_id' => '35', 'nama' => 'KABUPATEN PAMEKASAN'),
            array('id' => '3529', 'propinsi_id' => '35', 'nama' => 'KABUPATEN SUMENEP'),
            array('id' => '3571', 'propinsi_id' => '35', 'nama' => 'KOTA KEDIRI'),
            array('id' => '3572', 'propinsi_id' => '35', 'nama' => 'KOTA BLITAR'),
            array('id' => '3573', 'propinsi_id' => '35', 'nama' => 'KOTA MALANG'),
            array('id' => '3574', 'propinsi_id' => '35', 'nama' => 'KOTA PROBOLINGGO'),
            array('id' => '3575', 'propinsi_id' => '35', 'nama' => 'KOTA PASURUAN'),
            array('id' => '3576', 'propinsi_id' => '35', 'nama' => 'KOTA MOJOKERTO'),
            array('id' => '3577', 'propinsi_id' => '35', 'nama' => 'KOTA MADIUN'),
            array('id' => '3578', 'propinsi_id' => '35', 'nama' => 'KOTA SURABAYA'),
            array('id' => '3579', 'propinsi_id' => '35', 'nama' => 'KOTA BATU'),
            array('id' => '3601', 'propinsi_id' => '36', 'nama' => 'KABUPATEN PANDEGLANG'),
            array('id' => '3602', 'propinsi_id' => '36', 'nama' => 'KABUPATEN LEBAK'),
            array('id' => '3603', 'propinsi_id' => '36', 'nama' => 'KABUPATEN TANGERANG'),
            array('id' => '3604', 'propinsi_id' => '36', 'nama' => 'KABUPATEN SERANG'),
            array('id' => '3671', 'propinsi_id' => '36', 'nama' => 'KOTA TANGERANG'),
            array('id' => '3672', 'propinsi_id' => '36', 'nama' => 'KOTA CILEGON'),
            array('id' => '3673', 'propinsi_id' => '36', 'nama' => 'KOTA SERANG'),
            array('id' => '3674', 'propinsi_id' => '36', 'nama' => 'KOTA TANGERANG SELATAN'),
            array('id' => '5101', 'propinsi_id' => '51', 'nama' => 'KABUPATEN JEMBRANA'),
            array('id' => '5102', 'propinsi_id' => '51', 'nama' => 'KABUPATEN TABANAN'),
            array('id' => '5103', 'propinsi_id' => '51', 'nama' => 'KABUPATEN BADUNG'),
            array('id' => '5104', 'propinsi_id' => '51', 'nama' => 'KABUPATEN GIANYAR'),
            array('id' => '5105', 'propinsi_id' => '51', 'nama' => 'KABUPATEN KLUNGKUNG'),
            array('id' => '5106', 'propinsi_id' => '51', 'nama' => 'KABUPATEN BANGLI'),
            array('id' => '5107', 'propinsi_id' => '51', 'nama' => 'KABUPATEN KARANG ASEM'),
            array('id' => '5108', 'propinsi_id' => '51', 'nama' => 'KABUPATEN BULELENG'),
            array('id' => '5171', 'propinsi_id' => '51', 'nama' => 'KOTA DENPASAR'),
            array('id' => '5201', 'propinsi_id' => '52', 'nama' => 'KABUPATEN LOMBOK BARAT'),
            array('id' => '5202', 'propinsi_id' => '52', 'nama' => 'KABUPATEN LOMBOK TENGAH'),
            array('id' => '5203', 'propinsi_id' => '52', 'nama' => 'KABUPATEN LOMBOK TIMUR'),
            array('id' => '5204', 'propinsi_id' => '52', 'nama' => 'KABUPATEN SUMBAWA'),
            array('id' => '5205', 'propinsi_id' => '52', 'nama' => 'KABUPATEN DOMPU'),
            array('id' => '5206', 'propinsi_id' => '52', 'nama' => 'KABUPATEN BIMA'),
            array('id' => '5207', 'propinsi_id' => '52', 'nama' => 'KABUPATEN SUMBAWA BARAT'),
            array('id' => '5208', 'propinsi_id' => '52', 'nama' => 'KABUPATEN LOMBOK UTARA'),
            array('id' => '5271', 'propinsi_id' => '52', 'nama' => 'KOTA MATARAM'),
            array('id' => '5272', 'propinsi_id' => '52', 'nama' => 'KOTA BIMA'),
            array('id' => '5301', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SUMBA BARAT'),
            array('id' => '5302', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SUMBA TIMUR'),
            array('id' => '5303', 'propinsi_id' => '53', 'nama' => 'KABUPATEN KUPANG'),
            array('id' => '5304', 'propinsi_id' => '53', 'nama' => 'KABUPATEN TIMOR TENGAH SELATAN'),
            array('id' => '5305', 'propinsi_id' => '53', 'nama' => 'KABUPATEN TIMOR TENGAH UTARA'),
            array('id' => '5306', 'propinsi_id' => '53', 'nama' => 'KABUPATEN BELU'),
            array('id' => '5307', 'propinsi_id' => '53', 'nama' => 'KABUPATEN ALOR'),
            array('id' => '5308', 'propinsi_id' => '53', 'nama' => 'KABUPATEN LEMBATA'),
            array('id' => '5309', 'propinsi_id' => '53', 'nama' => 'KABUPATEN FLORES TIMUR'),
            array('id' => '5310', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SIKKA'),
            array('id' => '5311', 'propinsi_id' => '53', 'nama' => 'KABUPATEN ENDE'),
            array('id' => '5312', 'propinsi_id' => '53', 'nama' => 'KABUPATEN NGADA'),
            array('id' => '5313', 'propinsi_id' => '53', 'nama' => 'KABUPATEN MANGGARAI'),
            array('id' => '5314', 'propinsi_id' => '53', 'nama' => 'KABUPATEN ROTE NDAO'),
            array('id' => '5315', 'propinsi_id' => '53', 'nama' => 'KABUPATEN MANGGARAI BARAT'),
            array('id' => '5316', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SUMBA TENGAH'),
            array('id' => '5317', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SUMBA BARAT DAYA'),
            array('id' => '5318', 'propinsi_id' => '53', 'nama' => 'KABUPATEN NAGEKEO'),
            array('id' => '5319', 'propinsi_id' => '53', 'nama' => 'KABUPATEN MANGGARAI TIMUR'),
            array('id' => '5320', 'propinsi_id' => '53', 'nama' => 'KABUPATEN SABU RAIJUA'),
            array('id' => '5321', 'propinsi_id' => '53', 'nama' => 'KABUPATEN MALAKA'),
            array('id' => '5371', 'propinsi_id' => '53', 'nama' => 'KOTA KUPANG'),
            array('id' => '6101', 'propinsi_id' => '61', 'nama' => 'KABUPATEN SAMBAS'),
            array('id' => '6102', 'propinsi_id' => '61', 'nama' => 'KABUPATEN BENGKAYANG'),
            array('id' => '6103', 'propinsi_id' => '61', 'nama' => 'KABUPATEN LANDAK'),
            array('id' => '6104', 'propinsi_id' => '61', 'nama' => 'KABUPATEN MEMPAWAH'),
            array('id' => '6105', 'propinsi_id' => '61', 'nama' => 'KABUPATEN SANGGAU'),
            array('id' => '6106', 'propinsi_id' => '61', 'nama' => 'KABUPATEN KETAPANG'),
            array('id' => '6107', 'propinsi_id' => '61', 'nama' => 'KABUPATEN SINTANG'),
            array('id' => '6108', 'propinsi_id' => '61', 'nama' => 'KABUPATEN KAPUAS HULU'),
            array('id' => '6109', 'propinsi_id' => '61', 'nama' => 'KABUPATEN SEKADAU'),
            array('id' => '6110', 'propinsi_id' => '61', 'nama' => 'KABUPATEN MELAWI'),
            array('id' => '6111', 'propinsi_id' => '61', 'nama' => 'KABUPATEN KAYONG UTARA'),
            array('id' => '6112', 'propinsi_id' => '61', 'nama' => 'KABUPATEN KUBU RAYA'),
            array('id' => '6171', 'propinsi_id' => '61', 'nama' => 'KOTA PONTIANAK'),
            array('id' => '6172', 'propinsi_id' => '61', 'nama' => 'KOTA SINGKAWANG'),
            array('id' => '6201', 'propinsi_id' => '62', 'nama' => 'KABUPATEN KOTAWARINGIN BARAT'),
            array('id' => '6202', 'propinsi_id' => '62', 'nama' => 'KABUPATEN KOTAWARINGIN TIMUR'),
            array('id' => '6203', 'propinsi_id' => '62', 'nama' => 'KABUPATEN KAPUAS'),
            array('id' => '6204', 'propinsi_id' => '62', 'nama' => 'KABUPATEN BARITO SELATAN'),
            array('id' => '6205', 'propinsi_id' => '62', 'nama' => 'KABUPATEN BARITO UTARA'),
            array('id' => '6206', 'propinsi_id' => '62', 'nama' => 'KABUPATEN SUKAMARA'),
            array('id' => '6207', 'propinsi_id' => '62', 'nama' => 'KABUPATEN LAMANDAU'),
            array('id' => '6208', 'propinsi_id' => '62', 'nama' => 'KABUPATEN SERUYAN'),
            array('id' => '6209', 'propinsi_id' => '62', 'nama' => 'KABUPATEN KATINGAN'),
            array('id' => '6210', 'propinsi_id' => '62', 'nama' => 'KABUPATEN PULANG PISAU'),
            array('id' => '6211', 'propinsi_id' => '62', 'nama' => 'KABUPATEN GUNUNG MAS'),
            array('id' => '6212', 'propinsi_id' => '62', 'nama' => 'KABUPATEN BARITO TIMUR'),
            array('id' => '6213', 'propinsi_id' => '62', 'nama' => 'KABUPATEN MURUNG RAYA'),
            array('id' => '6271', 'propinsi_id' => '62', 'nama' => 'KOTA PALANGKA RAYA'),
            array('id' => '6301', 'propinsi_id' => '63', 'nama' => 'KABUPATEN TANAH LAUT'),
            array('id' => '6302', 'propinsi_id' => '63', 'nama' => 'KABUPATEN KOTA BARU'),
            array('id' => '6303', 'propinsi_id' => '63', 'nama' => 'KABUPATEN BANJAR'),
            array('id' => '6304', 'propinsi_id' => '63', 'nama' => 'KABUPATEN BARITO KUALA'),
            array('id' => '6305', 'propinsi_id' => '63', 'nama' => 'KABUPATEN TAPIN'),
            array('id' => '6306', 'propinsi_id' => '63', 'nama' => 'KABUPATEN HULU SUNGAI SELATAN'),
            array('id' => '6307', 'propinsi_id' => '63', 'nama' => 'KABUPATEN HULU SUNGAI TENGAH'),
            array('id' => '6308', 'propinsi_id' => '63', 'nama' => 'KABUPATEN HULU SUNGAI UTARA'),
            array('id' => '6309', 'propinsi_id' => '63', 'nama' => 'KABUPATEN TABALONG'),
            array('id' => '6310', 'propinsi_id' => '63', 'nama' => 'KABUPATEN TANAH BUMBU'),
            array('id' => '6311', 'propinsi_id' => '63', 'nama' => 'KABUPATEN BALANGAN'),
            array('id' => '6371', 'propinsi_id' => '63', 'nama' => 'KOTA BANJARMASIN'),
            array('id' => '6372', 'propinsi_id' => '63', 'nama' => 'KOTA BANJAR BARU'),
            array('id' => '6401', 'propinsi_id' => '64', 'nama' => 'KABUPATEN PASER'),
            array('id' => '6402', 'propinsi_id' => '64', 'nama' => 'KABUPATEN KUTAI BARAT'),
            array('id' => '6403', 'propinsi_id' => '64', 'nama' => 'KABUPATEN KUTAI KARTANEGARA'),
            array('id' => '6404', 'propinsi_id' => '64', 'nama' => 'KABUPATEN KUTAI TIMUR'),
            array('id' => '6405', 'propinsi_id' => '64', 'nama' => 'KABUPATEN BERAU'),
            array('id' => '6409', 'propinsi_id' => '64', 'nama' => 'KABUPATEN PENAJAM PASER UTARA'),
            array('id' => '6411', 'propinsi_id' => '64', 'nama' => 'KABUPATEN MAHAKAM HULU'),
            array('id' => '6471', 'propinsi_id' => '64', 'nama' => 'KOTA BALIKPAPAN'),
            array('id' => '6472', 'propinsi_id' => '64', 'nama' => 'KOTA SAMARINDA'),
            array('id' => '6474', 'propinsi_id' => '64', 'nama' => 'KOTA BONTANG'),
            array('id' => '6501', 'propinsi_id' => '65', 'nama' => 'KABUPATEN MALINAU'),
            array('id' => '6502', 'propinsi_id' => '65', 'nama' => 'KABUPATEN BULUNGAN'),
            array('id' => '6503', 'propinsi_id' => '65', 'nama' => 'KABUPATEN TANA TIDUNG'),
            array('id' => '6504', 'propinsi_id' => '65', 'nama' => 'KABUPATEN NUNUKAN'),
            array('id' => '6571', 'propinsi_id' => '65', 'nama' => 'KOTA TARAKAN'),
            array('id' => '7101', 'propinsi_id' => '71', 'nama' => 'KABUPATEN BOLAANG MONGONDOW'),
            array('id' => '7102', 'propinsi_id' => '71', 'nama' => 'KABUPATEN MINAHASA'),
            array('id' => '7103', 'propinsi_id' => '71', 'nama' => 'KABUPATEN KEPULAUAN SANGIHE'),
            array('id' => '7104', 'propinsi_id' => '71', 'nama' => 'KABUPATEN KEPULAUAN TALAUD'),
            array('id' => '7105', 'propinsi_id' => '71', 'nama' => 'KABUPATEN MINAHASA SELATAN'),
            array('id' => '7106', 'propinsi_id' => '71', 'nama' => 'KABUPATEN MINAHASA UTARA'),
            array('id' => '7107', 'propinsi_id' => '71', 'nama' => 'KABUPATEN BOLAANG MONGONDOW UTARA'),
            array('id' => '7108', 'propinsi_id' => '71', 'nama' => 'KABUPATEN SIAU TAGULANDANG BIARO'),
            array('id' => '7109', 'propinsi_id' => '71', 'nama' => 'KABUPATEN MINAHASA TENGGARA'),
            array('id' => '7110', 'propinsi_id' => '71', 'nama' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'),
            array('id' => '7111', 'propinsi_id' => '71', 'nama' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'),
            array('id' => '7171', 'propinsi_id' => '71', 'nama' => 'KOTA MANADO'),
            array('id' => '7172', 'propinsi_id' => '71', 'nama' => 'KOTA BITUNG'),
            array('id' => '7173', 'propinsi_id' => '71', 'nama' => 'KOTA TOMOHON'),
            array('id' => '7174', 'propinsi_id' => '71', 'nama' => 'KOTA KOTAMOBAGU'),
            array('id' => '7201', 'propinsi_id' => '72', 'nama' => 'KABUPATEN BANGGAI KEPULAUAN'),
            array('id' => '7202', 'propinsi_id' => '72', 'nama' => 'KABUPATEN BANGGAI'),
            array('id' => '7203', 'propinsi_id' => '72', 'nama' => 'KABUPATEN MOROWALI'),
            array('id' => '7204', 'propinsi_id' => '72', 'nama' => 'KABUPATEN POSO'),
            array('id' => '7205', 'propinsi_id' => '72', 'nama' => 'KABUPATEN DONGGALA'),
            array('id' => '7206', 'propinsi_id' => '72', 'nama' => 'KABUPATEN TOLI-TOLI'),
            array('id' => '7207', 'propinsi_id' => '72', 'nama' => 'KABUPATEN BUOL'),
            array('id' => '7208', 'propinsi_id' => '72', 'nama' => 'KABUPATEN PARIGI MOUTONG'),
            array('id' => '7209', 'propinsi_id' => '72', 'nama' => 'KABUPATEN TOJO UNA-UNA'),
            array('id' => '7210', 'propinsi_id' => '72', 'nama' => 'KABUPATEN SIGI'),
            array('id' => '7211', 'propinsi_id' => '72', 'nama' => 'KABUPATEN BANGGAI LAUT'),
            array('id' => '7212', 'propinsi_id' => '72', 'nama' => 'KABUPATEN MOROWALI UTARA'),
            array('id' => '7271', 'propinsi_id' => '72', 'nama' => 'KOTA PALU'),
            array('id' => '7301', 'propinsi_id' => '73', 'nama' => 'KABUPATEN KEPULAUAN SELAYAR'),
            array('id' => '7302', 'propinsi_id' => '73', 'nama' => 'KABUPATEN BULUKUMBA'),
            array('id' => '7303', 'propinsi_id' => '73', 'nama' => 'KABUPATEN BANTAENG'),
            array('id' => '7304', 'propinsi_id' => '73', 'nama' => 'KABUPATEN JENEPONTO'),
            array('id' => '7305', 'propinsi_id' => '73', 'nama' => 'KABUPATEN TAKALAR'),
            array('id' => '7306', 'propinsi_id' => '73', 'nama' => 'KABUPATEN GOWA'),
            array('id' => '7307', 'propinsi_id' => '73', 'nama' => 'KABUPATEN SINJAI'),
            array('id' => '7308', 'propinsi_id' => '73', 'nama' => 'KABUPATEN MAROS'),
            array('id' => '7309', 'propinsi_id' => '73', 'nama' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'),
            array('id' => '7310', 'propinsi_id' => '73', 'nama' => 'KABUPATEN BARRU'),
            array('id' => '7311', 'propinsi_id' => '73', 'nama' => 'KABUPATEN BONE'),
            array('id' => '7312', 'propinsi_id' => '73', 'nama' => 'KABUPATEN SOPPENG'),
            array('id' => '7313', 'propinsi_id' => '73', 'nama' => 'KABUPATEN WAJO'),
            array('id' => '7314', 'propinsi_id' => '73', 'nama' => 'KABUPATEN SIDENRENG RAPPANG'),
            array('id' => '7315', 'propinsi_id' => '73', 'nama' => 'KABUPATEN PINRANG'),
            array('id' => '7316', 'propinsi_id' => '73', 'nama' => 'KABUPATEN ENREKANG'),
            array('id' => '7317', 'propinsi_id' => '73', 'nama' => 'KABUPATEN LUWU'),
            array('id' => '7318', 'propinsi_id' => '73', 'nama' => 'KABUPATEN TANA TORAJA'),
            array('id' => '7322', 'propinsi_id' => '73', 'nama' => 'KABUPATEN LUWU UTARA'),
            array('id' => '7325', 'propinsi_id' => '73', 'nama' => 'KABUPATEN LUWU TIMUR'),
            array('id' => '7326', 'propinsi_id' => '73', 'nama' => 'KABUPATEN TORAJA UTARA'),
            array('id' => '7371', 'propinsi_id' => '73', 'nama' => 'KOTA MAKASSAR'),
            array('id' => '7372', 'propinsi_id' => '73', 'nama' => 'KOTA PAREPARE'),
            array('id' => '7373', 'propinsi_id' => '73', 'nama' => 'KOTA PALOPO'),
            array('id' => '7401', 'propinsi_id' => '74', 'nama' => 'KABUPATEN BUTON'),
            array('id' => '7402', 'propinsi_id' => '74', 'nama' => 'KABUPATEN MUNA'),
            array('id' => '7403', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KONAWE'),
            array('id' => '7404', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KOLAKA'),
            array('id' => '7405', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KONAWE SELATAN'),
            array('id' => '7406', 'propinsi_id' => '74', 'nama' => 'KABUPATEN BOMBANA'),
            array('id' => '7407', 'propinsi_id' => '74', 'nama' => 'KABUPATEN WAKATOBI'),
            array('id' => '7408', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KOLAKA UTARA'),
            array('id' => '7409', 'propinsi_id' => '74', 'nama' => 'KABUPATEN BUTON UTARA'),
            array('id' => '7410', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KONAWE UTARA'),
            array('id' => '7411', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KOLAKA TIMUR'),
            array('id' => '7412', 'propinsi_id' => '74', 'nama' => 'KABUPATEN KONAWE KEPULAUAN'),
            array('id' => '7413', 'propinsi_id' => '74', 'nama' => 'KABUPATEN MUNA BARAT'),
            array('id' => '7414', 'propinsi_id' => '74', 'nama' => 'KABUPATEN BUTON TENGAH'),
            array('id' => '7415', 'propinsi_id' => '74', 'nama' => 'KABUPATEN BUTON SELATAN'),
            array('id' => '7471', 'propinsi_id' => '74', 'nama' => 'KOTA KENDARI'),
            array('id' => '7472', 'propinsi_id' => '74', 'nama' => 'KOTA BAUBAU'),
            array('id' => '7501', 'propinsi_id' => '75', 'nama' => 'KABUPATEN BOALEMO'),
            array('id' => '7502', 'propinsi_id' => '75', 'nama' => 'KABUPATEN GORONTALO'),
            array('id' => '7503', 'propinsi_id' => '75', 'nama' => 'KABUPATEN POHUWATO'),
            array('id' => '7504', 'propinsi_id' => '75', 'nama' => 'KABUPATEN BONE BOLANGO'),
            array('id' => '7505', 'propinsi_id' => '75', 'nama' => 'KABUPATEN GORONTALO UTARA'),
            array('id' => '7571', 'propinsi_id' => '75', 'nama' => 'KOTA GORONTALO'),
            array('id' => '7601', 'propinsi_id' => '76', 'nama' => 'KABUPATEN MAJENE'),
            array('id' => '7602', 'propinsi_id' => '76', 'nama' => 'KABUPATEN POLEWALI MANDAR'),
            array('id' => '7603', 'propinsi_id' => '76', 'nama' => 'KABUPATEN MAMASA'),
            array('id' => '7604', 'propinsi_id' => '76', 'nama' => 'KABUPATEN MAMUJU'),
            array('id' => '7605', 'propinsi_id' => '76', 'nama' => 'KABUPATEN MAMUJU UTARA'),
            array('id' => '7606', 'propinsi_id' => '76', 'nama' => 'KABUPATEN MAMUJU TENGAH'),
            array('id' => '8101', 'propinsi_id' => '81', 'nama' => 'KABUPATEN MALUKU TENGGARA BARAT'),
            array('id' => '8102', 'propinsi_id' => '81', 'nama' => 'KABUPATEN MALUKU TENGGARA'),
            array('id' => '8103', 'propinsi_id' => '81', 'nama' => 'KABUPATEN MALUKU TENGAH'),
            array('id' => '8104', 'propinsi_id' => '81', 'nama' => 'KABUPATEN BURU'),
            array('id' => '8105', 'propinsi_id' => '81', 'nama' => 'KABUPATEN KEPULAUAN ARU'),
            array('id' => '8106', 'propinsi_id' => '81', 'nama' => 'KABUPATEN SERAM BAGIAN BARAT'),
            array('id' => '8107', 'propinsi_id' => '81', 'nama' => 'KABUPATEN SERAM BAGIAN TIMUR'),
            array('id' => '8108', 'propinsi_id' => '81', 'nama' => 'KABUPATEN MALUKU BARAT DAYA'),
            array('id' => '8109', 'propinsi_id' => '81', 'nama' => 'KABUPATEN BURU SELATAN'),
            array('id' => '8171', 'propinsi_id' => '81', 'nama' => 'KOTA AMBON'),
            array('id' => '8172', 'propinsi_id' => '81', 'nama' => 'KOTA TUAL'),
            array('id' => '8201', 'propinsi_id' => '82', 'nama' => 'KABUPATEN HALMAHERA BARAT'),
            array('id' => '8202', 'propinsi_id' => '82', 'nama' => 'KABUPATEN HALMAHERA TENGAH'),
            array('id' => '8203', 'propinsi_id' => '82', 'nama' => 'KABUPATEN KEPULAUAN SULA'),
            array('id' => '8204', 'propinsi_id' => '82', 'nama' => 'KABUPATEN HALMAHERA SELATAN'),
            array('id' => '8205', 'propinsi_id' => '82', 'nama' => 'KABUPATEN HALMAHERA UTARA'),
            array('id' => '8206', 'propinsi_id' => '82', 'nama' => 'KABUPATEN HALMAHERA TIMUR'),
            array('id' => '8207', 'propinsi_id' => '82', 'nama' => 'KABUPATEN PULAU MOROTAI'),
            array('id' => '8208', 'propinsi_id' => '82', 'nama' => 'KABUPATEN PULAU TALIABU'),
            array('id' => '8271', 'propinsi_id' => '82', 'nama' => 'KOTA TERNATE'),
            array('id' => '8272', 'propinsi_id' => '82', 'nama' => 'KOTA TIDORE KEPULAUAN'),
            array('id' => '9101', 'propinsi_id' => '91', 'nama' => 'KABUPATEN FAKFAK'),
            array('id' => '9102', 'propinsi_id' => '91', 'nama' => 'KABUPATEN KAIMANA'),
            array('id' => '9103', 'propinsi_id' => '91', 'nama' => 'KABUPATEN TELUK WONDAMA'),
            array('id' => '9104', 'propinsi_id' => '91', 'nama' => 'KABUPATEN TELUK BINTUNI'),
            array('id' => '9105', 'propinsi_id' => '91', 'nama' => 'KABUPATEN MANOKWARI'),
            array('id' => '9106', 'propinsi_id' => '91', 'nama' => 'KABUPATEN SORONG SELATAN'),
            array('id' => '9107', 'propinsi_id' => '91', 'nama' => 'KABUPATEN SORONG'),
            array('id' => '9108', 'propinsi_id' => '91', 'nama' => 'KABUPATEN RAJA AMPAT'),
            array('id' => '9109', 'propinsi_id' => '91', 'nama' => 'KABUPATEN TAMBRAUW'),
            array('id' => '9110', 'propinsi_id' => '91', 'nama' => 'KABUPATEN MAYBRAT'),
            array('id' => '9111', 'propinsi_id' => '91', 'nama' => 'KABUPATEN MANOKWARI SELATAN'),
            array('id' => '9112', 'propinsi_id' => '91', 'nama' => 'KABUPATEN PEGUNUNGAN ARFAK'),
            array('id' => '9171', 'propinsi_id' => '91', 'nama' => 'KOTA SORONG'),
            array('id' => '9401', 'propinsi_id' => '94', 'nama' => 'KABUPATEN MERAUKE'),
            array('id' => '9402', 'propinsi_id' => '94', 'nama' => 'KABUPATEN JAYAWIJAYA'),
            array('id' => '9403', 'propinsi_id' => '94', 'nama' => 'KABUPATEN JAYAPURA'),
            array('id' => '9404', 'propinsi_id' => '94', 'nama' => 'KABUPATEN NABIRE'),
            array('id' => '9408', 'propinsi_id' => '94', 'nama' => 'KABUPATEN KEPULAUAN YAPEN'),
            array('id' => '9409', 'propinsi_id' => '94', 'nama' => 'KABUPATEN BIAK NUMFOR'),
            array('id' => '9410', 'propinsi_id' => '94', 'nama' => 'KABUPATEN PANIAI'),
            array('id' => '9411', 'propinsi_id' => '94', 'nama' => 'KABUPATEN PUNCAK JAYA'),
            array('id' => '9412', 'propinsi_id' => '94', 'nama' => 'KABUPATEN MIMIKA'),
            array('id' => '9413', 'propinsi_id' => '94', 'nama' => 'KABUPATEN BOVEN DIGOEL'),
            array('id' => '9414', 'propinsi_id' => '94', 'nama' => 'KABUPATEN MAPPI'),
            array('id' => '9415', 'propinsi_id' => '94', 'nama' => 'KABUPATEN ASMAT'),
            array('id' => '9416', 'propinsi_id' => '94', 'nama' => 'KABUPATEN YAHUKIMO'),
            array('id' => '9417', 'propinsi_id' => '94', 'nama' => 'KABUPATEN PEGUNUNGAN BINTANG'),
            array('id' => '9418', 'propinsi_id' => '94', 'nama' => 'KABUPATEN TOLIKARA'),
            array('id' => '9419', 'propinsi_id' => '94', 'nama' => 'KABUPATEN SARMI'),
            array('id' => '9420', 'propinsi_id' => '94', 'nama' => 'KABUPATEN KEEROM'),
            array('id' => '9426', 'propinsi_id' => '94', 'nama' => 'KABUPATEN WAROPEN'),
            array('id' => '9427', 'propinsi_id' => '94', 'nama' => 'KABUPATEN SUPIORI'),
            array('id' => '9428', 'propinsi_id' => '94', 'nama' => 'KABUPATEN MAMBERAMO RAYA'),
            array('id' => '9429', 'propinsi_id' => '94', 'nama' => 'KABUPATEN NDUGA'),
            array('id' => '9430', 'propinsi_id' => '94', 'nama' => 'KABUPATEN LANNY JAYA'),
            array('id' => '9431', 'propinsi_id' => '94', 'nama' => 'KABUPATEN MAMBERAMO TENGAH'),
            array('id' => '9432', 'propinsi_id' => '94', 'nama' => 'KABUPATEN YALIMO'),
            array('id' => '9433', 'propinsi_id' => '94', 'nama' => 'KABUPATEN PUNCAK'),
            array('id' => '9434', 'propinsi_id' => '94', 'nama' => 'KABUPATEN DOGIYAI'),
            array('id' => '9435', 'propinsi_id' => '94', 'nama' => 'KABUPATEN INTAN JAYA'),
            array('id' => '9436', 'propinsi_id' => '94', 'nama' => 'KABUPATEN DEIYAI'),
            array('id' => '9471', 'propinsi_id' => '94', 'nama' => 'KOTA JAYAPURA'),
        );

        DB::table('kota')->insert($kota);
    }
}